// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVStNe4yvK3-exnvAXVydy6F51_Hn9pOg',
    appId: '1:701131617654:web:0376ac452ded7b0718b657',
    messagingSenderId: '701131617654',
    projectId: 'prepowl-dev',
    authDomain: 'prepowl-dev.firebaseapp.com',
    storageBucket: 'prepowl-dev.appspot.com',
    measurementId: 'G-K7MNC1Z19S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgftcAPxfzfZ1-CTg9zpDv62m9bBa6ARU',
    appId: '1:701131617654:android:8161f46ae7a672ab18b657',
    messagingSenderId: '701131617654',
    projectId: 'prepowl-dev',
    storageBucket: 'prepowl-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGv6HkCki1YhOJPXEQSV7OYbh2Gz_Ioos',
    appId: '1:701131617654:ios:c28dbe2f6b67b62218b657',
    messagingSenderId: '701131617654',
    projectId: 'prepowl-dev',
    storageBucket: 'prepowl-dev.appspot.com',
    iosClientId: '701131617654-p7m2v05iuk3g9biqebsdn9clvtqlrbn4.apps.googleusercontent.com',
    iosBundleId: 'com.shikhar.prepowl.dev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGv6HkCki1YhOJPXEQSV7OYbh2Gz_Ioos',
    appId: '1:701131617654:ios:de84b6ea47acd08818b657',
    messagingSenderId: '701131617654',
    projectId: 'prepowl-dev',
    storageBucket: 'prepowl-dev.appspot.com',
    iosClientId: '701131617654-rtvh5gfh9n6mptmpgkfv4hvglknofsr2.apps.googleusercontent.com',
    iosBundleId: 'com.shikhar.prepowl',
  );
}
