// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6wxTBuWGdRkz-6p0g0cYmYZxZhGgVl9c',
    appId: '1:751204660427:web:624408346c73312887174e',
    messagingSenderId: '751204660427',
    projectId: 'prepowl-staging',
    authDomain: 'prepowl-staging.firebaseapp.com',
    storageBucket: 'prepowl-staging.appspot.com',
    measurementId: 'G-82NWRXGXKT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzRgwwxXXlXVEyYJpB7EIIwKkFFZUmpe4',
    appId: '1:751204660427:android:57f9a8ba5671a14d87174e',
    messagingSenderId: '751204660427',
    projectId: 'prepowl-staging',
    storageBucket: 'prepowl-staging.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIQOi2LM1NYFELtjjMJfs7ET0hwAht5n0',
    appId: '1:751204660427:ios:5bcb09e6ff7ec91f87174e',
    messagingSenderId: '751204660427',
    projectId: 'prepowl-staging',
    storageBucket: 'prepowl-staging.appspot.com',
    iosClientId: '751204660427-svi8gpvdok20rlu7fgktrqft6amd4g4i.apps.googleusercontent.com',
    iosBundleId: 'com.shikhar.prepowl.staging',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIQOi2LM1NYFELtjjMJfs7ET0hwAht5n0',
    appId: '1:751204660427:ios:a6eff27ef5d2fa3387174e',
    messagingSenderId: '751204660427',
    projectId: 'prepowl-staging',
    storageBucket: 'prepowl-staging.appspot.com',
    iosClientId: '751204660427-heiku1l4hrjqpbsbrg111pugrh2lsji1.apps.googleusercontent.com',
    iosBundleId: 'com.shikhar.prepowl',
  );
}
